development:
  adapter: redis

test:
  adapter: redis

homeion:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: dealit_homeion

production:
  adapter: redis
  url: <%= ENV["REDISCLOUD_URL"] %>
